# Site settings
title: root@An00bRektn:~/blog#
description: "Not Another Infosec/Computer Science/stuff Blog"
baseurl: "/" # for test: remove string '/space-jekyll-template' to ''
url: "https://an00brektn.github.io" # for test: remove string 'http://victorvoid.github.io' to '' but in production: 'https://yourusername.github.io'

# User settings
username: An00bRektn
user_title: An00bRektn
email: rsyed.business404@gmail.com
twitter_username: An00bRektn
github_username:  An00bRektn
#gplus_username:  loremipsum
#linkedin_public_url: loremipsum # Example: For public profile 'www.linkedin.com/in/john-smith', 'john-smith' is your linkedin_public_url
#disqus_username: loremipsum
profile_picture: https://avatars2.githubusercontent.com/u/58986498?s=460&u=ae50f9e5e53e1b2402d7702abdef2d0492cb8958&v=4

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  section_1:
    - title: home
      url: /
      key_trigger: 1
    - title: my posts
      url: /posts
      key_trigger: 2
    #- title: series
    #  url: /series
    #  key_trigger: 3
    - title: tags
      url: /tags
      key_trigger: 3
    - title: about me
      url: /about
      key_trigger: 4
  section_2:
    - title: github
      url: https://www.github.com/An00bRektn
      new_tab: true
      key_trigger: g
      external: true
    - title: twitter
      url: http://www.twitter.com/An00bRektn
      key_trigger: t
      external: true
    - title: search
      url: ""
      key_trigger: s #WARNING: search only works with "s"

# projects in header index
projects:
  - name: Gopher47
    url: https://github.com/An00bRektn/gopher47
  - name: Flyer CTF
    url: https://github.com/An00bRektn/flyer-ctf
  - name: Malware Analysis Reports
    url: https://github.com/An00bRektn/malware-analysis-reports
 

# exclude my node related stuff
exclude: ['package.json', 'src/js', 'src/styl', 'node_modules']

# Google Analytics
google_analytics: G-0FL142RMXL